# 1. Tensors

In [1]:
import torch
import numpy as np

텐서는 numpy의 array랑 똑같다고 생각하면 된다. 다른 점은 텐서는 GPU로의 연산이 가능해 계산을 가속할 수 있다. 우리는 이 텐서를 모델의 input, output 그리고 parameter로 사용할 것이다.

### Tensor initializaiton
텐서는 다양한 방법으로 만들 수 있는데 첫번째는 데이터(List, array)를 직접 가져오는 것이다.

In [4]:
data = [[1,2],[3,4]]
tensor = torch.tensor(data)
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [5]:
array = np.array(data)
tensor = torch.tensor(array)
print(tensor)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


두번째는 넘파이와 같이 특정 숫자의 element들을 가지는 tensor을 만들 수 있다.
like 애들은 텐서를 넣어주면 같은 size를 가진 텐서를 반환해준다.

In [6]:
t_ones = torch.ones_like(tensor)  ## 텐서를 넣고 해당 텐서와 같은 size를 가진 텐서를 반환
print(t_ones)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [7]:
t_rand = torch.rand_like(tensor, dtype=torch.float)  ## [0,1)의 random sample을 반환
print(t_rand)

tensor([[0.1375, 0.0834],
        [0.1737, 0.5616]])


Size만 넣어줘서 특정 형태의 텐서를 만들어주는 것은 넘파이랑 똑같다.

In [8]:
size = (2,3)

random_tensor = torch.rand(size)
one_tensor = torch.ones(size)
zero_tensor = torch.zeros(size)
print( random_tensor,"\n", one_tensor, "\n",zero_tensor)

tensor([[0.9250, 0.5985, 0.5122],
        [0.7285, 0.7026, 0.7047]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes
텐서들의 attributes를 파악해 텐서의 사이즈, dtype, device를 알 수 있다.

In [9]:
tensor = torch.zeros((2,2))

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 2])
torch.float32
cpu


### Tensor Operation

텐서에 수많은 operation들이 가능하다. 먼저 텐서 연산들을 빠르게 하기 위해 이를 GPU로 보내면 좋다.

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(tensor.device)

cuda:0


Numpy array와 같이 텐서를 indexing 및 slicing이 가능하다.

In [11]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


또 cat 함수를 통해 concat할 수 있음.

In [18]:
t1 = torch.cat([tensor, tensor], dim=1)
t2 = torch.cat([tensor, tensor], dim=0)
print(t1,'\n',t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서간의 element-wise 곱연산은 두가지 방법으로 가능하다.

In [20]:
print(tensor.mul(tensor))
print(tensor*tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


dot-product는 넘파이랑 똑같음

In [22]:
print(tensor.matmul(tensor))
print(tensor@tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])
tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


변수 자체를 바꾸는 inplace operator가 존재한다. Inplace operator는 memory save측면에서 도움이 되지만 history가 사라진다는 점에서 잘 쓰이진 않는다.

In [23]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])